pipeline:
  name: SBOM Drift for React Store
  identifier: SBOM_Drift_for_React_Store
  projectIdentifier: Product_Exploratory
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.tejakummarikuntla
        repoName: react-store
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: Install_dependencies
                  spec:
                    connectorRef: account.harnessImage
                    image: node/node:14
                    shell: Sh
                    command: |
                      rm -rf ./node_modules package-lock.json
                      npm install
              - step:
                  type: SscaOrchestration
                  name: Generate SBOM
                  identifier: Generate_SBOM
                  spec:
                    mode: generation
                    tool:
                      type: Syft
                      spec:
                        format: spdx-json
                    source:
                      type: repository
                      spec:
                        url: https://github.com/tejakummarikuntla/react-store
                        variant_type: branch
                        variant: main
                    resources:
                      limits:
                        memory: 500Mi
                        cpu: "0.5"
